name: Deployment Workflow
on:
  push:
    branches: [master]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        host: prajna-github-secrets
        username: prajna
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
    - name: Adding known hosts
      run: ssh-keyscan -H ${{secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      script: |
        source django_env/bin/activate
        cd myproject
        git pull origin master 
        git status
          
